### ISSUE TITLE
prebuilt binary for aarch64 platform

### ISSUE THREAD

**Issue by dawnmy** [ITBE-Lab/MA#14]
Thank you for developing such an useful tool. It works very well for me on x86 servers/computers. But recently we have server based on aarch64. I tried to compile and install MA on it, but did not succeed. I was wondering if there will be a prebuilt binary available to download or install via conda for aarch64? 

Best,
Zhi-Luo

**Comment by MarkusRainerSchmidt** [comment]
Hi,

Unfortunately, kswcpp - the dynamic programming library we use - relies on SIMD instructions that are not supported by aarach64.
Due to the work required for resolving this, we currently have no plans to make MA compatible with this architecture.


Sorry,

Arne and Markus
