### ISSUE TITLE
Can I use MA to align assembled contig to the reference genome?

### ISSUE THREAD

**Issue by dawnmy** [ITBE-Lab/MA#15]
thank you for developing this nice aligner. I was wondering what is the recommended range of query length for MA? Can it be used to align assembled contigs with length up to 10M bases to the reference genome? If it is fine, which parameter setting is recommended?

**Comment by MarkusRainerSchmidt** [comment]
Hi,

The recommended range for queries basically covers the sizes you can get from Illumina, PacBio, and Nanopore sequencing reads.

Fully assembled contigs go beyond that range.

However, I would assume they would just work using the 'Nanopore' presetting if you are willing to accept the limitations that come from the way read-aligners operate: 
They assume that most of the read will align without structural variants (SV) to find the best mapping for a read.
While there is some tolerance towards SVs (using Supplementary Alignments), this is rather limited.

I think that a dedicated genome-to-genome aligner would give you better results with full contigs.


Cheers,

Markus
